{% set name = "docstring_parser" %}
{% set version = "0.15" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 48ddc093e8b1865899956fcc03b03e66bb7240c310fac5af81814580c55bf682

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.6,<4.0
  run:
    - python >=3.6


test:
  imports:
    - docstring_parser
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/rr-/docstring_parser
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: 'Parse Python docstrings in reST and Google format '
  description: |
    Parse Python docstrings. Currently support ReST, Google, and Numpydoc-style
    docstrings.
  dev_url: https://github.com/rr-/docstring_parser

extra:
  recipe-maintainers:
    - Chilipp
    - rr-
    - thewchan
